/* eslint-disable react-native/no-color-literals */
import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    row: {
        height: 80,
        width: '100%',
        padding: 8,
        justifyContent: 'space-between',
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#fdfdfd',
      },
      hidden: {
        width: '100%',
        justifyContent: 'flex-end',
        flexDirection: 'row',
      },
      add: {
        width: 80,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#1dcc74',
      },
      checkout: {
        width: 80,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'tomato',
      },
      icon: {
        width: 24,
        height: 24,
      },
      maintitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fdfdfd',
      },
      title: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
      },
      subtitle: {
        fontSize: 12,
        color: '#888',
      },
      total: {
        fontSize: 12,
        color: '#1dcc74',
      },
      price: {
        fontSize: 18,
        color: '#1dcc74',
      },
      header: {
        backgroundColor: '#ffbc2d',
      },
      fab: {
        backgroundColor: 'tomato',
        margin: 8,
      },
      fabbutton: {
        backgroundColor: '#ffbc2d',
      },
      closebutton: {
        backgroundColor: 'tomato',
        height: 24,
        width: 24,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        fontSize: 12,
        color: '#fff',
        top: 15,
        right: 15,
      },
      modalcontainer: {
        height: '100%',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
      },
      newordercontent: {
        padding: 25,
        borderRadius: 5,
        elevation: 5,
        width: '85%',
        height: '35%',
        backgroundColor: '#fff',
      },
      opentablebutton: {
        backgroundColor: '#ffbc2d',
        position: 'relative',
        bottom: 0,
        justifyContent: 'center',
        overflow: 'scroll',
      },
      showdetailsdate: {
        fontSize: 10,
        color: 'gray',
      },
      addproductscontent: {
        paddingVertical: 30,
        paddingHorizontal: 10,
        borderRadius: 5,
        elevation: 5,
        width: '95%',
        height: '95%',
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
      },
      pizzalarge: {
        width: 60,
        height: 60,
        alignSelf: 'center',
      },
      pickicon: {
        width: 120,
        height: 120,
        alignSelf: 'center',
      },
      pizzamedium: {
        width: 50,
        height: 50,
        alignSelf: 'center',
      },
      pizzasmall: {
        width: 40,
        height: 40,
        alignSelf: 'center',
      },
      pizzaitem: {
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        marginVertical: 15,
        height: 120,
        width: '100%',
      },
      pizzasizes: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        width: '100%',
      },
      pizzaflavorsearch: {
        borderColor: 'whitesmoke',
        borderWidth: 1,
        borderRadius: 5,
        height: 40,
        flex: 0,
        width: '100%',
        marginBottom: 15,
      },
      pizzaflavortags: {
        maxHeight: 60,
        borderWidth: 1,
        borderColor: 'whitesmoke',
        marginVertical: 8,
      },
      pizzaflavortagscontainer: {
        alignContent: 'center',
        alignItems: 'center',
        height: '100%'
      },
      center: {
        textAlign: 'center',
      },
      separator: {
        height: 32,
        width: '100%',
        backgroundColor: 'whitesmoke',
        justifyContent: 'center',
        alignItems: 'center',
      },
      flavorcontainer: {
        height: '100%',
        width: '100%',
        position: 'relative',
        padding: 30,
        backgroundColor: '#fff',
        elevation: 5
      },
      tagcontainer: {
        flex: 1,
        borderRadius: 5,
        borderColor: 'silver',
        borderWidth: 1,
        padding: 5,
        marginVertical: 15,
      },
      tagitem: {
        alignSelf: 'flex-start',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        padding: 8,
        borderRadius: 5,
        borderColor: 'whitesmoke',
        borderWidth: 1,
      },
      tagclosebutton: {
        height: 30,
        marginLeft: 3,
      },
      flavorlistitem: {
        alignItems: 'center',
        justifyContent: 'center',
        height: 40,
        borderColor: 'whitesmoke',
        borderRadius: 5,
        borderWidth: 1,
        margin: 3,
      },
      flavorlistitemtext: {
        color: '#777',
      },
})